countertops/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

urlpatterns = [
    path('',views.get_all_countertops,name='get_all_countertops'),
    path('<filter>',views.get_filtered_countertops,name='get_filtered_countertops')
]

magicstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from countertops import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.show_main_page),
    path('contact',views.open_contact_form, name='open_contact_form'),
    path('about',views.get_about_page, name='get_about_page'),
    # path('countertops/',include('countertops.urls')),
    url(r'^countertops/', include(('countertops.urls', 'countertops'), namespace='countertops')),
    url(r'^slabs/', include(('slabs.urls', 'slabs'), namespace='slabs')),
    url(r'^sinks/', include(('sinks.urls', 'sinks'), namespace='sinks')),
]

sinks/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

urlpatterns = [
    path('',views.get_all_sinks,name='get_all_sinks'),
    path('<sink_id>',views.get_sink_id,name='get_sink_id'),

]

slabs/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

urlpatterns = [
    path('<material>', views.get_all_slabs_material, name='get_all_slabs_material'),
    path('<material>/<category>', views.get_material_category_slab, name='get_material_category_slab'),
    path('<material>/<category>/<id>', views.get_countertop_by_id, name='get_countertop_by_id'),

    # path('<filter>',views.get_filtered_countertops,name='get_filtered_countertops')
]

countertops/models.py
from django.db import models

CATEGORY_CHOICES = (
    ('kitchen','Kitchen'),
    ('vanity', 'Vanity'),
    ('island','Island'),
    ('fireplace','Fireplace'),
    ('custom','Custom'),
)

# Create your models here.
class Countertop(models.Model):
    title = models.CharField(max_length=255)
    category = models.CharField(max_length=255, choices=CATEGORY_CHOICES, default='kitchen')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='static/countertops')

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Index(models.Model):
    title = models.CharField(max_length=255)

class IndexImages(models.Model):
    index_ids = models.ForeignKey(Index, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/img')

sinks/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
SINK_CATEGORY = (
    ('undermount', 'Undermount Sink'),
    ('topmount', 'Top-Mount Sink'),
    ('double_bowl', 'Double Bowl Sink'),
    ('sinkgle_bowl', 'Single Bowl Sink'),
    ('porcelain', 'Porcelain Sink'),
)


class Sink(models.Model):

    title = models.CharField(max_length=255)
    sink_category = models.CharField(max_length=255, choices=SINK_CATEGORY,default='undermount')
    sink_image = models.ImageField(upload_to='static/sinks')
    sink_text = RichTextField(blank=True, null=True)

    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

slabs/models.py
from django.db import models

# Create your models here.
SLAB_MATERIAL_CHOICES = (
    ('quartz', 'Quartz'),
)

SLAB_CATEGORY_CHOICES = (
    ('concrete', 'Concrete'),
    ('calcata', 'Calcata'),
    ('marble', 'Marble'),
    ('exotic', 'Exotic'),
    ('classic', 'Classic'),
    ('sparkling', 'Sparkling'),
)


class Slab(models.Model):

    title = models.CharField(max_length=255)
    slab_material = models.CharField(max_length=255, choices=SLAB_MATERIAL_CHOICES, default='quartz')
    slab_category = models.CharField(max_length=255, choices=SLAB_CATEGORY_CHOICES, default='concrete')
    slab_thikness = models.CharField(max_length=255)
    slab_size = models.CharField(max_length=255)
    slab_finish = models.CharField(max_length=255,blank=True)

    description = models.TextField(blank=True)

    slab_image = models.ImageField(upload_to='static/slabs')
    slab_close_image = models.ImageField(upload_to='static/slabs',blank=True)

    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class SlabWorkExample(models.Model):

    item_ids = models.ForeignKey(Slab, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/slabs')

    created_date = models.DateTimeField(auto_now_add=True)

countertops/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from .models import Countertop,IndexImages

# Create your views here.

def show_main_page(request):
    index_images = IndexImages.objects.filter(index_ids=1)
    view_template = 'countertops/index.html'
    print(index_images)
    context = {'images':index_images}

    return render(request,view_template,context)

def open_contact_form(request):
    view_template = 'countertops/contact.html'

    return render(request,view_template)

def get_all_countertops(request):
    countertops_list = Countertop.objects.all().order_by('-created')
    view_template = 'countertops/countertop-list.html'
    countext = {'countertops':countertops_list,'filter':'all','link':'countertops'}

    return render(request, view_template, countext)


def get_filtered_countertops(request,filter):
    countertops_list = Countertop.objects.filter(category=filter)

    view_template = 'countertops/countertop-list.html'
    countext = {'countertops': countertops_list,'filter':filter,'link':'countertops'}

    return render(request,view_template,countext)

def get_about_page(request):
    view_template = 'countertops/about.html'
    return render(request,view_template)

sinks/views.py
from django.shortcuts import render
from .models import Sink

# Create your views here.
def get_all_sinks(request):
    all_sinks = Sink.objects.all().order_by('-created_date')
    view_template = 'sinks/sink-list.html'
    context = {'sink_list':all_sinks,'filter':'sinks'}

    return render(request,view_template,context)

def get_sink_id(request,sink_id):
    get_sink_id = Sink.objects.get(id=sink_id)
    print(sink_id)
    print(get_sink_id)
    print(get_sink_id.title)
    view_tempalte = 'sinks/sink.html'
    context = {'sink':get_sink_id,'filter':'sinks'}

    return render(request,view_tempalte,context)

slabs/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.mail import send_mail, BadHeaderError
from .models import Slab, SlabWorkExample
# Create your views here.


def get_all_slabs_material(request,material):
    print(material)
    slabs_list = Slab.objects.filter(slab_material=material).order_by('-created_date')
    print(slabs_list)
    view_template = 'slabs/slab-list.html'
    context = {'slabs':slabs_list,'filter':'quartz','link':'slabs'}

    return render(request,view_template,context)

def get_material_category_slab(request,material,category):
    slab_list = Slab.objects.filter(slab_material=material,slab_category=category).order_by('-created_date')
    view_template = 'slabs/slab-list.html'
    context = {'slabs':slab_list,'filter':category,'link':'slabs'}

    return render(request,view_template,context)

def get_countertop_by_id(request,material,category,id):
    view_template = 'slabs/slab.html'

    if request.method == 'POST':
        message_name = request.POST.get('name', '')
        message_email = request.POST.get('email', '')
        message = request.POST.get('message', '')

        # print(message_name)
        # return render(request, view_template, {'message_name': message_name})

        if message_name and message and message_email:
            try:
                send_mail('Sent from site', message, message_email, ['info@magicstone.ca'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return render(request,view_template,{'message_name':message_name})

    slab_ids = Slab.objects.get(id=id)
    slab_works = SlabWorkExample.objects.filter(item_ids=id)

    # print(material)
    # print(id)
    context = {'slab':slab_ids, 'slab_works':slab_works,'link':'slabs'}

    return render(request,view_template,context)

countertops/templates/countertops/about.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="container-about">
        <div class="center-div">
            <h1 class="about-title">Modern quartz solutions for your home</h1>
            <img class="about-small-width" style="margin-top: 10px;" src="/static/img/countertop-example.jpg"
                 alt="countertop example"/>
            <p class="about-text about-small-width" style="margin-top: 10px">
                <strong><u>Magicstone</u></strong> offers customization services for quartz products in GTA and all
                Ontario
                province. From kitchen countertops to fireplaces, from bars to bathroom decoration, we offer a variety
                of
                solutions for your home. We also do:
            </p>

            <div class="about-square-left">
                <img style="margin-top: 10px;" src="/static/img/countertop-example.jpg" alt="countertop example"/>
                <p class="about-text" style="margin-top: 10px; padding: 10px; margin-left: 10px">
                    <strong><u>Magicstone</u></strong> offers customization services for quartz products in GTA and all
                    Ontario
                    province. From kitchen countertops to fireplaces, from bars to bathroom decoration, we offer a
                    variety
                    of
                    solutions for your home.
                </p>
            </div>
            <h1 id="we-also-do">We also do:</h1>
            <ul class="list">
                <li>Backsplashes</li>
                <li>Tub surrounds</li>
                <li>Vanities</li>
                <li>Custom projects</li>
                <li>Slab sales</li>
                <li>Sell sink faucets</li>
            </ul>
            <h1 class="about-title">Why Quartz?</h1>
            <img class="about-small-width" style="margin-top: 10px;" src="/static/img/TypesofCountertops-min.jpg"
                 alt="countertops type"/>
            <p class="about-small-width" style="margin-top: 20px;">
                <strong><u>Quartz countertops</u></strong> have become an elegant decision for those who love the look
                of
                granite but are concerned about the maintenance. Quartz is stronger than granite, requires no resealing
                & is
                highly resistant to scratches and stains. Visit our showroom to view samples of all the major brands of
                quartz colors we have. After choosing the right slab for you, we will go with you through all process
                from
                idea & design to installation on your site. Our <strong>rule #1</strong> is <u>satisfaction of our
                customers</u>
            </p>
            <div class="about-square-right">

                <p style="margin-top: 20px; margin-left: 0; max-width: 435px;">
                    <strong><u>Quartz countertops</u></strong> have become an elegant decision for those who love the
                    look
                    of
                    granite but are concerned about the maintenance. Quartz is stronger than granite, requires no
                    resealing
                    & is
                    highly resistant to scratches and stains. Visit our showroom to view samples of all the major brands
                    of
                    quartz colors we have. After choosing the right slab for you, we will go with you through all
                    process
                    from
                    idea & design to installation on your site. Our <strong>rule #1</strong> is <u>satisfaction of our
                    customers</u>
                </p>
                <img style="margin-top: 10px;" src="/static/img/TypesofCountertops-min.jpg" alt="countertops type"/>

            </div>
            <h1 class="about-title">Why Magicstone?</h1>
            {#        <h3 class="about-subtitle">We are:</h3>#}
            <ul class="list" style="list-style-type: decimal;">
                <li>Locally Owned & Operated</li>
                <li>Have fast turnaround team</li>
                <li>In our showroom, you can find an extensive range of quartz options in variable textures, patterns
                    and
                    colours
                </li>
                <li>The quartz we supply has the perfect combination of visual appeal and desirable properties</li>
                <li>We provide excellent customer service and make sure that our clients have a satisfying experience.
                </li>
                <li>No Sub-contractors Involved</li>
            </ul>
            <h1 class="about-title">Our Service Process:</h1>

            <div class="square">
                <div>
                    <img style="margin-top: 10px; height: 100px; width: 70px" src="/static/img/installer-icon.png"
                         alt="countertop installer"/>
                </div>

                <p>
                    After you schedule a consultation, one of our quartz specialists will meet you in your place or in
                    our
                    showroom.
                    You will be welcomed to share all your ideas and Then they take
                    measurements and give you free estimate.
                    Once you’ve chosen the style you want, we fabricate the quartz slab according to your preferences.
                    Finally,
                    we arrange a convenient time and date for you to deliver and install your stone.
                </p>
            </div>
        </div>
    </div>
    {% include 'base/footer.html' %}
{% endblock %}

countertops/templates/countertops/contact.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <form style="margin-top: 20px;">
            <div class="form-group">
                <input type="text" class="form-control" id="nameInput" placeholder="NAME">
                <input style="margin-top: 20px" type="email" class="form-control" id="emailInput" placeholder="YOUR EMAIL">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                    else.</small>
            </div>
            <div class="form-group">
                <textarea rows="8" class="form-control" id="messageInput" placeholder="MESSAGE"></textarea>
            </div>

            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
    </div>

    {% include 'base/footer.html' %}
{% endblock %}

countertops/templates/countertops/countertop-list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="countertop-list" style="margin-top: 20px">
            {% if countertops %}
                {% for countertop in countertops %}
                    {% if countertop.image %}
                        <a href="{{ countertop.image.url }}">
                            <div class="cards">
                                <img class="card-img-top" src="{{ countertop.image.url }}" alt="Card image cap">
                            </div>
                        </a>

                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>

    {% include 'base/footer.html' %}
{% endblock %}

countertops/templates/countertops/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            {% for image in images %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <div class="d-flex align-items-center justify-content-center min-vh-100 corousel-div"
                         style="background-image: url({{ image.image.url }})">
                    </div>

                </div>
            {% endfor %}
        </div>
    </div>


    <script>
        $(document).ready(function () {
            var header = $('#header-main').height()
            var windowHeight = $(window).height() - header;
            windowHeight = windowHeight + 49
            $('.carousel-inner').css('height', windowHeight + 'px');
            $('.corousel-div').css('background-size', $(window).width() + 'px ' + windowHeight + 'px')
            $('.corousel-div').css('background-repeat', 'no-repeat')
            $('.corousel-div').css('min-height', 'no-repeat')
            if ($(window).height() > $(window).width()) {
                $('.corousel-div').css('background-size', windowHeight + 354 + 'px ' + windowHeight + 'px')
                $('.corousel-div').css('background-position-x', 'center')
            }


            $(window).resize(function () {
                var header = $('#header-main').height()
                var windowHeight = $(window).height() - header;
                windowHeight = windowHeight + 49
                $('.carousel-inner').css('height', windowHeight + 'px');
                $('.corousel-div').css('background-size', $(window).width() + 'px ' + windowHeight + 'px')
                $('.corousel-div').css('background-repeat', 'no-repeat')
                $('.corousel-div').css('min-height', 'no-repeat')
                if ($(window).height() > $(window).width()) {
                    $('.corousel-div').css('background-size', windowHeight + 354 + 'px ' + windowHeight + 'px')
                    $('.corousel-div').css('background-position-x', 'center')
                }
            })
        });
    </script>
{% endblock %}

sinks/templates/sinks/sink-list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="sink-container">
        <h1 class="sink-title">Sink & Faucets</h1>
        <div class="sink-list">
            {% for sink in sink_list %}
                <a href="{% url 'sinks:get_sink_id' sink.id %}">
                    <div class="sink-card">
                        {% if sink.sink_image %}
                            <img src="{{ sink.sink_image.url }}">
                        {% endif %}
                        <h3 style="margin-top: 20px;" class="sink-category">{{ sink.get_sink_category_display }}</h3>
                        <p class="sink-description">{{ sink.sink_text | safe | truncatewords:25 }}</p>

                    </div>
                </a>
            {% endfor %}
        </div>
    </div>

    {% include 'base/footer.html' %}
{% endblock %}

sinks/templates/sinks/sink.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="sink-container-details">
        <h1 class="sink-title"></h1>
        <h1 class="sink-title">{{ sink.title }}</h1>
        <div class="sink">
            {% if sink.sink_image %}
                <img src="{{ sink.sink_image.url }}">
            {% endif %}

            <h3 class="sink-category" style="margin-top: 20px">{{ sink.get_sink_category_display }}</h3>
            <p class="sink-description">{{ sink.sink_text | safe }}</p>

        </div>

        <div class="contact-us">
            <h3 class="text-left">Have questions?</h3>
            <h5 class="text-left">Contact Us</h5>
            <br/>
            <form method="post">{% csrf_token %}
                <div class="form-group">
                    {#                <label for="exampleInputEmail1">Name</label>#}
                    <input type="text" name="name" class="form-control" id="nameInput" placeholder="NAME">
                    <input style="margin-top: 20px" name="email" type="email" class="form-control"
                           id="emailInput"
                           placeholder="EMAIL">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small>
                </div>
                <div class="form-group">
                            <textarea rows="8" class="form-control" name="message" id="messageInput"
                                      placeholder="MESSAGE"></textarea>
                </div>

                <button type="submit" class="btn btn-warning">Submit</button>
                <br/>
            </form>
        </div>

    </div>

    {% include 'base/footer.html' %}
{% endblock %}

slabs/templates/slabs/slab-list.html
{% extends 'base/base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <div class="slabs-list">
            {% if slabs %}
                {% for slab in slabs %}
                    {% if slab.slab_image %}

                        <div class="card" style="margin-top: 20px;">
                            <a href="{% url 'slabs:get_countertop_by_id' slab.slab_material slab.slab_category slab.id %}">
                                <img class="card-img-top"
                                     src="{{ slab.slab_image.url }}"
                                     alt="Card image cap">
                                <div class="card-body">
                                    <h5 class="card-title">{{ slab.title }}</h5>
                                    <p class="card-text">Thickness: {{ slab.slab_thikness }}</p>
                                    <p class="card-text">Slab Sizes: <br/> {{ slab.slab_size }}</p>
                                    {% if slab.slab_finish %}
                                        <p class="card-text">Finished: {{ slab.slab_finish }}</p>{% endif %}
                                </div>
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
    {% include 'base/footer.html' %}
    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/simplelightbox/2.7.0/simple-lightbox.min.js" integrity="sha512-ZajFBgnksNp8Rj+AbmYe8ueOu45HiSjtf3QpqnRbHlq719m6VK0FkbYIqQ8wEnlVuJ1i9pC+z6Z9ewmDnUTMCg==" crossorigin="anonymous"></script>#}
    {##}
    {#    <script>#}
    {#        var gallery = new SimpleLightbox('.photo_gallery a');#}
    {#    </script>#}
{% endblock %}

templates/base/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <title>Magicstone | Quartz countertops and custom solutions for you</title>
    <meta name="description" content="Magicstone offers customization services for quartz products in GTA and all Ontario
            province. From kitchen countertops to fireplaces, from bars to bathroom decoration, we offer a variety of
            solutions for your home">
    <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1">
    <meta property="og:url" content="https://magicstone.ca"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e4d8bb73a2.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    {#    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simplelightbox/2.7.0/simple-lightbox.css"
          integrity="sha512-8WAX0xL/cHZ38RXoX2gtuqkAwmDVAzGwoFVmHvn46IDHGWOjTHx0vcl9OapNrfOzpFtql0SNkv+0y0b5Fm8ZkA=="
          crossorigin="anonymous"/>



</head>
<body>
{% include 'base/basestyles.html' %}
{% include 'base/header.html' %}
{#<script src="/static/slabs/jquery-loupe-min.js"/>#}
{#<hr/>#}


{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
{#JQuary-Confirm#}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
{#<script>#}
{#    $('#test-img').loupe({#}
{#        width: 200, // width of magnifier#}
{#        height: 150, // height of magnifier#}
{#        loupe: 'loupe' // css class for magnifier#}
{#    });#}
{#</script>#}

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="/static/slabs/jquery.loupe.js"></script>

{#<script type="text/javascript">$('.demo').loupe();</script>#}
</body>
</html>

templates/base/basestyles.html
{% load static %}
{% load compress %}

{% compress css %}
    <link type="text/x-scss" href="{% static 'scss/header.scss' %}" rel="stylesheet" media="screen">
    <link type="text/x-scss" href="{% static 'scss/index.scss' %}" rel="stylesheet" media="screen">
    <link type="text/x-scss" href="{% static 'scss/countertops.scss' %}" rel="stylesheet" media="screen">
    <link type="text/x-scss" href="{% static 'scss/slabs.scss' %}" rel="stylesheet" media="screen">
    <link type="text/x-scss" href="{% static 'scss/contact.scss' %}" rel="stylesheet" media="screen">
    <link type="text/x-scss" href="{% static 'scss/footer.scss' %}" rel="stylesheet" media="screen">
    <link type="text/x-scss" href="{% static 'scss/about.scss' %}" rel="stylesheet" media="screen">
    <link type="text/x-scss" href="{% static 'scss/sink.scss' %}" rel="stylesheet" media="screen">
{% endcompress %}

templates/base/footer.html
<div class="footer">
    {#    <hr style="background-color: #6c757d; width: 75%"/>#}
    <h4 style="color:#f4be35;">MAGICSTONE</h4>
    <div class="footer-info">
        <div class="foot-left">
            <h5>Hours: </h5>
            <p>Monday - Friday :<br/> 8am - 6pm <br/> Saturday: <br/> By appointment only <br/> Sun: Closed</p>
            <h5 style="margin: 0; margin-top: 5px;">Address:</h5>
            <a href="https://www.google.ca/maps/place/185+Doughton+Rd,+Concord,+ON+L4K+1R1/@43.7920814,-79.523232,17z/data=!3m1!4b1!4m5!3m4!1s0x882b2fb17df243f7:0xa49a62e9b548590!8m2!3d43.7920775!4d-79.5210433"><i
                    class="fas fa-map-marker-alt"></i> 185 Doughton Rd, Concord, ON L4K 1R1</a> <br/>
        </div>
        <div class="foot-right">
            <h5>Tel:</h5>
            <a href="tel:(416) 704-1404">(416) 704-1404</a>
            <br/>
            <a href="tel:(467) 701-1109">(647) 701-1109</a>
            <h5 style="margin: 0; margin-top: 5px;">Email:</h5>
            <a href="mailto:info@magicstone.ca">info@magicstone.ca</a>
        </div>
        <div class="foot-social">
            <h5>Socials:</h5>
            <a class="nav-link" href="https://www.facebook.com/Magic-stone-1547591812006405/"><i
                    style="font-size: 20px;" class="fab fa-facebook-square"></i></a>
            <br/>
            <a class="nav-link" href="https://www.instagram.com/magicstone.ca/"><i style="font-size: 20px;"
                                                                                   class="fab fa-instagram"></i></a>
        </div>
    </div>
    <br/>
    <small>&#169; Magicstone {% now "Y" %} All rights reserved.</small>
    {#    <ul class="contacts-ul">#}
    {#        <li style="text-align: left">Hours:</li>#}
    {#        <li style="display: inline-block; margin-right: 5px;">Mn - Fr: 9AM - 6PM</li>#}
    {#        <li style="display: inline-block; margin-left: 5px;">St: 10AM - 1PM</li>#}
    {#        <li style="display: inline-block; margin-right: 5px;">Phone: +1 111-111-1111</li>#}
    {#        <li style="display: inline-block; margin-left: 5px;">Email: info@magicstone.ca</li>#}
    {#        <li>Address: 185 Doughton Rd, Concord, ON L4K 1R1</li>#}
    {#    </ul>#}
    {#    <small>&#169; Magicstone {% now "Y" %} All rights reserved.</small>#}
</div>